Warmline/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main_app.urls'))
]

main_app/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^submitQuery/', views.submit_query, name='submit_query'),
    url(r'^submitQueryReply/$', views.expert_view, name='submitQueryReply'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^expert/$', views.expert_view, name='home'),
    url(r'^setExpertView/$', views.set_expert_view, name='setExpertView'),
    url(r'^searchQueryView/$', views.search_query, name='searchQueryView'),
    url(r'^setGroup/$', views.set_group, name='setGroup'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^receiveAudio/', views.receive_audio, name='receive'),
    url(r'^report/$', views.generate_report, name='report'),
    # url(r'^localhostLogin/$', views.localhostLogin, name='locahostLogin'),
    url(r'^replySatisfaction/(?P<replyHash>\w{64})/(?P<queryId>[0-9]+)/$', views.process_reply_satisfaction, name='replySatisfaction')
]

main_app/models.py
from django.db import models
from main_app.choices import *
from django.core.validators import RegexValidator
from datetime import datetime
from django.contrib.auth.models import User
# Create your models here.

# FOR EXPERTS
class Expert(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile_regex = RegexValidator(regex=r'^\+\d{12}$')
    mobile_no = models.CharField(validators=[mobile_regex], max_length=13, blank=True, null=True)
    last_chosen = models.BooleanField(default=False, null=False)


# FOR NORMAL DOCTORS
class Query(models.Model):
    name = models.CharField(max_length=50, default='', blank=False, null=False)
    qualification = models.CharField(max_length=4, choices=QUALIFICATION_CHOICE, blank=False, null=False, default=1)
    qual_add_info = models.CharField(max_length=50, blank=True, default=None, null=True)
    practice_type = models.IntegerField(default=1, choices=PRACTICE_TYPE_CHOICE, blank=False, null=False)
    area_of_practice = models.TextField(max_length=100, blank=False, null=False)
    mobile_regex = RegexValidator(regex=r'^\d{10}$')
    mobile_no = models.CharField(validators=[mobile_regex], max_length=13, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)
    query = models.TextField(blank=False, null=False)
    query_start_time = models.DateTimeField(blank=True, null=False)
    expert_assigned = models.ForeignKey(Expert, on_delete=models.CASCADE, default=None, null=True)
    needReply = models.BooleanField(default=True, null=False, blank=True)
    resolved = models.BooleanField(default=False, null=False, blank=True)
    satisfaction_link_is_alive = models.BooleanField(default=False, null=False, blank=True)
    satisfaction = models.IntegerField(choices=SATISFACTION_CHOICE, null=True, blank=True)


class Reply(models.Model):
    query = models.ForeignKey(Query, on_delete=models.CASCADE, default=None, null=True)
    expert = models.ForeignKey(Expert, on_delete=models.CASCADE, default=None, null=True)
    reply = models.TextField(blank=False, null=False)
    reply_extra = models.TextField(blank=True, null=True, default=None)
    reply_datetime = models.DateTimeField(blank=True, null=True)

main_app/forms.py
from django import forms
from django.forms import ModelForm, Textarea, CharField, TextInput
from django.core.exceptions import ValidationError
from main_app.models import Query
from main_app.choices import *


class LocalhostLoginForm(forms.Form):
    email = forms.EmailField(label="Email:")
    password = forms.CharField(widget=forms.PasswordInput())

class QueryForm(ModelForm):
    practice_type = forms.ChoiceField(widget=forms.RadioSelect, choices=PRACTICE_TYPE_CHOICE)
    class Meta:
        model = Query
        exclude = ['query_start_time', 'expert_assigned', 'reply', 'reply_extra', 'previous_experts', 'resolved',
                   'needReply', 'final_reply_receive_time', 'satisfaction', 'satisfaction_link_is_alive']
        labels = {
            'qual_add_info': 'Expertise'
        }
        widgets = {
            'area_of_practice': Textarea(attrs={'class': 'materialize-textarea', 'placeholder': 'Delhi'}),
            'qual_add_info': TextInput(attrs={'disabled': ''}),
            'mobile_no': TextInput(attrs={'placeholder': '9876543210'}),
            'query': Textarea(attrs={'class': 'materialize-textarea'}),
        }
    def clean(self):
        if self.cleaned_data.get('qualification') != "MBBS" and self.cleaned_data.get('qual_add_info') == None:
            self.add_error('qual_add_info', 'This field is required')
            # raise ValidationError("Fill additional details field")
        return self.cleaned_data


class ReplyForm(forms.Form):
    queryId = forms.IntegerField(widget=forms.HiddenInput())
    reply = forms.CharField(label="Reply", widget=forms.Textarea(attrs={
        'class': 'materialize-textarea',
        'placeholder': 'Enter reply here',
    }))
    reply_extra = forms.CharField(required=False, label='Extra Comments (optional)',
                                  widget=forms.Textarea(attrs={
                                      'class': 'materialize-textarea',
                                      'placeholder': 'To refer to another expert, enter information here'
                                  }))



class SetExpertForm(forms.Form):
    queryId = forms.IntegerField(widget=forms.HiddenInput())
    expertId = forms.IntegerField(widget=forms.HiddenInput())

main_app/templates/expertSearchResultQuery.html
{% load tz %}
<style>
    @media only screen and (max-width: 500px){
        strong{
            font-weight: bold;
        }
        .searched-query-header{
            margin-top: 100px;
        }
        .searched-query-provider-name{
            margin-top: 0px !important;
        }
    }
</style>
<div class="query-collection-header searched-query-header"><p style="font-size: 24px;">Searched Query</p></div>
<div class="provider-name searched-query-provider-name" style="margin-top: 80px;">
    <b>
            <span class="querySno grey-text text-darken-1" style="font-size: 1.3rem">
                #{{ searchQuery.id }}
            </span>
        Provider Name:
    </b>
    {{ searchQuery.name }}
</div>
<div class="card query-collection-item" style="padding: 10px;">
    <div class="row">

        <div class="provider-qualification col l6 m6 s12">
            <b>Qualification: </b><br>
            {% if searchQuery.qualification == "SPC" %}
                Specialist
            {% elif searchQuery.qualification == "Other" %}
                Other
            {% else %}
                MBBS
            {% endif %}
            {% if searchQuery.qual_add_info != None %}
                ({{ searchQuery.qual_add_info }})
            {% endif %}
        </div>
        <div class="provider-email col l6 m6 s12">
            <b>Email: </b><br>{{ searchQuery.email }}
        </div>
    </div>
    <div class="row area-of-practice col s12" style="margin-left: 5px;">
        <b>Area of Practice: </b>{{ searchQuery.area_of_practice }}
    </div>
    <div class="row query-details" style="margin: 0">
        <div class="row" style="margin: 0 0 5px 0 ;">
            <div class="col s2"><b>Query:</b></div>
        </div>
        <div class="query grey lighten-3"
             style="border-radius: 3px; padding: 2px 5px 5px 5px; margin: 0 7px;">
            {{ searchQuery.query|linebreaks }}
        </div>
    </div>
    <div class="row query-start-time" style="margin: 10px 10px 5px 10px;">
        <div>
            <b>Query Initiated
                on: </b>{{ searchQuery.query_start_time|timezone:"Asia/Kolkata" }}
        </div>
    </div>
    <div class="reply-container" style="margin: 10px 10px 5px 10px;">
        <div class="row reply-header" style="margin: 0 0 5px 0;">
            <div><b>Previous Replies:</b></div>
        </div>
        <div class="row reply-body"
             style="border-left: 3px #316DAC solid; border-radius: 3px; padding-left: 5px;">
            {% for reply in searchReplies %}
                <div class="reply-content grey lighten-3" data-present="True"
                     style="padding: 5px 5px; margin-top: 20px; border-left: 3px #ff9800 solid; border-radius: 3px;">
                    <div class="reply-expert-name">
                        <strong>Expert Name:</strong>
                        Dr. {{ reply.expert.user.first_name }} {{ reply.expert.user.last_name }}
                    </div>

                    <div class="reply-content">
                        <strong>Reply: </strong>
                        {{ reply.reply|linebreaks }}
                    </div>
                    {% if reply.reply_extra != None and reply.reply_extra != "" %}
                        <div class="reply-extra">
                            <strong>Extra Comments: </strong>
                            {{ reply.reply_extra|linebreaks }}
                        </div>
                    {% endif %}
                    <div class="reply-time">
                        <strong>Reply Time: </strong>
                        {{ reply.reply_datetime|timezone:"Asia/Kolkata" }}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="row query-feedback-{{ forloop.counter }}">
        <form class="col s12" queryId="{{ searchQuery.id }}" name="replyForm" id="replyForm--1">
            {% csrf_token %}
            {% for field in replyForm.visible_fields %}
                <div class="input-field">
                    {{ field }}
                    <label class="active" for="{{ field.auto_id }}">{{ field.label }}</label>
                    <b><span class="helper-text" helper-for="{{ field.name }}--1"></span></b>
                </div>
            {% endfor %}
            {% for field in replyForm.hidden_fields %}
                {{ field }}
            {% endfor %}
            <div button-for="-1" class="replyFormSubmitButton btn waves-effect green waves-yellow">
                <div class="preloader-container" style="display: flex; align-items: center;">
                    <div class="preloader" style="display: flex;"></div>
                    <div class="loader-text-data">Send Reply</div>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $(".replyFormSubmitButton").click(function () {
        idx = $(this).attr("button-for");
        frm = $("#replyForm-" + idx);
        queryId = frm.attr("queryId");
        replyFormSubmitButtonAction(idx, frm, queryId);
    });
</script>

main_app/templates/headImports.html
<!--Import Google Icon Font-->
{% load static %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!--Import materialize.css-->
<link rel="stylesheet" href="{% static 'css/materialize.css' %}">
<link rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
<!--Let browser know website is optimized for mobile-->
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<style>
    @media only screen and (max-width: 500px){
        strong{
            font-weight: bold;
        }
    }
</style>

main_app/templates/index.html
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Pukaar</title>
        {% include 'headImports.html' %}
    </head>
    <body>
    <style>
        @media only screen and (max-width: 500px) {
            .mainButtonContainer > a{
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                margin-top: 20px;
            }
        }
    </style>
    <div class="master-container container">
        <div class="service-name" style="text-align: center;">
            <h2>Pukaar</h2>
        </div>
        <div class="mainButtonContainer">
            <button data-target="queryFormModal" class="btn waves-light modal-trigger blue">Ask a Query</button>
            {% if user.is_authenticated %}
                <a class="btn red lighten-2 waves-effect waves-light" href={% url 'logout' %}>Logout</a>
            {% else %}
                <a class="btn red waves-effect waves-light" href="{% url 'social:begin' 'google-oauth2' %}">
                    Expert Login
                </a>
            {% endif %}
        </div>
{#        <div class="localhostLogin">#}
{#            <form action="{% url 'locahostLogin' %}" method="post">#}
{#                {% csrf_token %}#}
{#                {{ localhostLoginForm }}#}
{#                <input type="submit" class="btn" value="Login"/>#}
{#            </form>#}
{#        </div>#}

        <div id="queryFormModal" class="modal modal-fixed-footer queryFormContainer">
            <div class="modal-content row" style="padding: 10px;">
                {% include 'queryForm.html' %}
            </div>
            <div class="modal-footer">
                <a href="" class="btn-flat modal-action modal-close waves-effect waves-red">Cancel</a>
{#                <button class="btn-flat waves-effect waves-green">Submit Query</button>#}
                <div class="btn waves-effect submitQueryButton myBtn">
                    <div class="preloader-container" style="display: flex; align-items: center;">
                        <div class="preloader"></div>
                        <div class="loader-text-data">Submit Query</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
        .master-container{
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            height: 100vh;
        }
        :root{
            --success-color: #2e7d32 !important;
            --loader-360-color: #a5d6a7 !important;
        }

        .preloader {
            display: none;
        }
        .submitQueryButton{
            background-color: #03a9f4;
        }
        .submitQueryButton:hover{
            background-color: #4fc3f7;
        }
    </style>

    {% include 'jsImports.html' %}
    <script>
        var selectElem = document.querySelector('select');
        var selectInstance = M.Select.init(selectElem);
        var modalElem = document.querySelector('.modal');
        var modalInstance = M.Modal.init(modalElem);
    </script>
    <script>
        $(".submitQueryButton").click(function(event){
            event.preventDefault();
            frm = $('#queryForm');

            document.querySelector(".submitQueryButton").style.backgroundColor = "#8bc34a";
            preloader = document.querySelector(".preloader");
            preloader.innerHTML = "{% filter escapenewline %}{% filter addslashes %}{% include 'preloaders/loader_with_tick.html' %}{% endfilter %}{% endfilter %}";
            preloader.style.display = "flex";
            preloader.querySelector(".checkmark").style.display = "none";
            preloader.querySelector(".circle-loader").classList.remove('load-complete');
            document.querySelector(".loader-text-data").innerHTML = "Sending";

            $.ajax({
                type: frm.attr('method'),
                url: frm.attr('action'),
                data: frm.serialize(),
                success: function (data, status, xhr) {
                    var ct = xhr.getResponseHeader("content-type") || "";
                    if(ct.indexOf('json') > -1){
                        keys = Object.keys(data);
                        $("span[helper-for]").html("");
                        for(i=0;i<keys.length;i++){
                            $("span[helper-for="+keys[i]+"]").html(Object.values(data)[i]);
                        }
                        document.querySelector(".loader-text-data").innerHTML = "Error";
                        document.querySelector(".submitQueryButton").style.backgroundColor = "#f44336";
                        document.querySelector(".preloader").style.display = "none";
                    }
                    else{
                        document.querySelector(".submitQueryButton").style.backgroundColor = "#4caf50";
                        document.querySelector(".loader-text-data").innerHTML = "Sent";
                        document.querySelector(".circle-loader").classList.toggle('load-complete');
                        document.querySelector(".checkmark").style.display = "block";
                        setTimeout(function(){M.toast({html: data}); modalInstance.close();}, 1500);
                    }

                },
                error: function(response){
                    keys = Object.keys(response);
                    for(i=0;i<keys.length;i++){
                        console.log(keys[i], Object.values(response)[i]);
                    }

                }
            });
        });
        qualField = $("select[name='qualification']");
        qualField.change(function(){
            qual_add_info_TextField = $("input[name='qual_add_info']");

            if($("select[name='qualification'] option:selected").text() === "MBBS"){
                qual_add_info_TextField.attr('disabled', '');
                qual_add_info_TextField.css("cursor", "not-allowed");
                qual_add_info_TextField.siblings().css("cursor", "not-allowed");
                qual_add_info_TextField.parent().css("cursor", "not-allowed");
                $("input[name='qual_add_info']").val("");
                $("label[for='id_qual_add_info']").removeClass("active");
                $("span[helper-for='qual_add_info']").html("");
            }
            else{
                qual_add_info_TextField.removeAttr("disabled");
                qual_add_info_TextField.prop("required", true);
                qual_add_info_TextField.css("cursor", "initial");
                qual_add_info_TextField.siblings().css("cursor", "initial");
                qual_add_info_TextField.parent().css("cursor", "initial");
            }
        });
    </script>
    </body>
</html>

main_app/templates/jsImports.html
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{#<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>#}
<script src="{% static 'js/materialize.js' %}"></script>

main_app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

main_app/templates/queryForm.html
<form action="{% url 'submit_query' %}" method="post" id="queryForm" class="col s12">
    {% csrf_token %}
    {% for field in queryForm %}

        {% if  forloop.counter <= 3 %}
            <div class="input-field col s4">
        {% elif forloop.counter == 4 %}
            <div class="input-field col l5 m6 s12">
        {% elif forloop.counter == 5 %}
            <div class="input-field col l7 m6 s12">
        {% else %}
            <div class="input-field col s12">
        {% endif %}

        {% if forloop.counter != 4 %}
                {{ field }}
                <label for="{{ field.auto_id }}">{{ field.label }}</label>
                <strong><span class="helper-text" helper-for="{{ field.name }}"></span></strong>
        {% else %}
                <div class="radioGroup row" style="display: flex; margin-top: 10px; margin-left: 0; justify-content: space-between; align-items: center">
                    <div><strong class="grey-text">{{ field.label }}:</strong></div>
                    {% for choice in queryForm.practice_type.field.choices %}
                        <div>
                            <label for="{{ field.auto_id }}_{{ forloop.counter }}">
                                <input name="{{ field.name }}" id="{{ field.auto_id }}_{{ forloop.counter }}" required
                                       value="{{ choice.0 }}" type="radio" {% if forloop.counter == 1 %}checked{% endif %}/>
                                <span>{{ choice.1 }}</span>
                            </label>
                        </div>
                    {% endfor %}
                    <strong><span class="helper-text" helper-for="{{ field.name }}"></span></strong>
                </div>
        {% endif %}
            </div>
    {% endfor %}
</form>

main_app/templates/searchbar.html
{% load custom_filters %}
<div class="searchResultContainer container">

</div>
<div class="searchBarContainer">
    <nav>
        <div class="nav-wrapper white">
            <form>
                <div class="input-field">
                    <form>
                    <input class="search" id="search" placeholder="Enter query number here" type="search" oninput="this.value=this.value.replace(/[^0-9]/g,'');">
                    </form>
                        <label class="label-icon" for="search"><i class="material-icons black-text">search</i></label>
                </div>
            </form>
        </div>
    </nav>
</div>
<style>
    .searchBarContainer {
        border-radius: 3px;
        z-index: 10;
        position: fixed;
        width: 300px;
        top: 110px;
        right: -245px;
        transition: right .25s ease-in-out
    }

    .searchBarContainer:hover {
        transition: right .25s ease-in-out;
        right: 0 !important
    }
</style>
<script>
    searchContainer = $("#search");
    searchContainer
        .focusin(function () {
            $(".searchBarContainer").css({
                right: "0px"
            })
        })
        .focusout(function () {
            this.value = this.value.replace(/^\s+|\s+$/g, "");
            customRightval = 14 * this.value.length;
            customRightval > 245 && (customRightval = 245);
            $(".searchBarContainer").css({right: "calc(-245px + " + customRightval + "px)"});
        });
</script>
<script>
    searchContainer = $("#search");
    searchContainer.keyup(function(){
        searchQueryId = searchContainer.val();
        if(searchQueryId !== ""){
            $(".defaultQueryContainer").hide();
            $(".searchResultContainer").show();
            {#$(".searchResultContainer").html("{% filter escapenewline %}{% filter addslashes %}{% include "preloaders/normal_loader.html" %}{% endfilter %}{% endfilter %}");#}
            $.ajax({
                type: "GET",
                url: {% url 'searchQueryView' %},
                data: {searchQueryId: searchQueryId, userHash: "{{ userHash }}"},
                success: function (response) {
                    $(".searchResultContainer").html(response).css({"display": "", "height": "", "text-align": "left"});
                },
                error: function (response) {
                    $(".searchResultContainer").html("<h4>No such query exists</h4>")
                        .css({
                            "display":"flex", "justify-content":"center", "align-items":"center",
                            "height":"calc(100vh - 48px - 1.52rem)", "flex-direction":"column", "text-align": "center"
                        });
                }
            });
        }
        else{
            $(".searchResultContainer").hide();
            $(".searchResultContainer").html("");
            $(".defaultQueryContainer").show();
        }
    });
</script>

main_app/templates/thankyouForFeedback.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Pukaar</title>
        {% include 'headImports.html' %}
    </head>
    <body>
        <div class="master-container container" style="height: 100vh; display: flex; justify-content: center; align-items: center;">
            <div class="service-name" style="text-align: center;">
                {% if data == "yes" %}
                    <h3>Thankyou for the response, your query has been closed.</h3>
                    <p style="font-size: 18px;">Thankyou for using Pukaar</p>
                {% elif data == "expired"%}
                    <h3>The link has expired.</h3>
                    <p style="font-size: 18px;">Thankyou for using Pukaar</p>
                {% elif data == "no"%}
                    <h3>We are sorry that the response wasn't satisfactory.</h3>
                    <p style="font-size: 18px;">A new expert will be assigned to your query and you will be kept updated.</p>
                {% endif %}
            </div>
        </div>
        {% include 'jsImports.html' %}
    </body>
</html>